### ISSUE TITLE
Documentation checklist

### ISSUE THREAD

**Issue by alec-hoyland** [sg-s/xolotl#326]
Documentation that still needs to be done:

- [x] How to
  - [x] Inject current
  - [x] Make your own components
    - [x] Creating a new conductance by hand
    - [x] Creating new mechanisms
    - [x] Creating new synapses
- [ ] Reference
  - [x] cpplab Properties
  - [ ] conductance properties
- [ ] How xolotl works
  - [ ] How cpplab binds code
  - [x] How equations are integrated
    - [x] The Exponential Euler method
    - [x] The RK4 method
    - [x] The Euler method
    - [x] The Crank-Nicholson method
  - [ ] How xolotl transpiles code
  - [x] How xolotl interfaces with its binary
  - [x] How hashing works in xolotl and cpplab
- [ ] Performance tips
  - [ ] Memory

**Comment by sg-s** [comment]
This checklist is out of date
